### ISSUE TITLE
Heart Localization step - execution error

### ISSUE THREAD

**Issue by dalmouiee** [AIM-Harvard/DeepCAC#7]
Hello, I'm trying to run the ```run_step1_heart_localization.py``` however I'm getting the following error when the script tries to load the weights into the model:
```
Deep Learning model inference using cpu only:
Loading saved model from "/workspaces/DeepCAC/data/step1_heartloc/model_weights/step1_heartloc_model_weights.hdf5"
Compiling single CPU model...
Traceback (most recent call last):
  File "run_step1_heart_localization.py", line 153, in <module>
    weights_file_name = weights_file_name)
  File "/workspaces/DeepCAC/src/step1_heartloc/run_inference.py", line 150, in run_inference
    pkl_file, test_file, weights_file, mgpu, has_manual_seg, export_png)
  File "/workspaces/DeepCAC/src/step1_heartloc/run_inference.py", line 66, in test
    model.load_weights(weights_file)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/training.py", line 162, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/network.py", line 1424, in load_weights
    saving.load_weights_from_hdf5_group(f, self.layers)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 737, in load_weights_from_hdf5_group
    ' layers.')
ValueError: You are trying to load a weight file containing 1 layers into a model with 19 layers.
```

Changes that I've made to the dependent scripts include:

- Changing the model setup from multi GPU to a single CPU one, as I don't have any GPUs on my machine. I changed the ```mgpu = 1```, so a CPU setup should work with the logic implemented in your code. 

It could be a keras versioning issue but I'm not sure. Is it possible to get a list of the required python libraries with their versioning also?  I currently have the latest version of Keras and other libraries and your pipeline uses python2 (which has been outdated for a while now), so having a list of the versions might solve the issue for me.

Thanks!

**Comment by dalmouiee** [comment]
I might add that the error seems to be saying that there is a discrepancy between the weights in the ```step1_heartloc_model_weights.hdf5``` and the model defined in the ```heartloc_model.py```. Could the model, from which the saved weights were extracted, be different to the architecture defined in ```heartloc_model.py```?

**Comment by dalmouiee** [comment]
Waiting on #2, closing issue
